### ISSUE TITLE
Linux config missing from git clone

### ISSUE THREAD

**Issue by jiminorris** [ultrastares/usdxworldparty#24]
Running the autogen script on linux does not generate the configurations and make files to install the game

`Updating build configuration files for Ultrastar Deluxe WorldParty, please wait...
./autogen.sh: 10: ./autogen.sh: autoreconf: not found
./install: 3: ./install: ./configure: not found
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for 'install'.
`

**Comment by TeLiXj** [comment]
You must execute ./install instead of autogen.sh directly.
Maybe don't work at all, I had troubles with last Kubuntu 19.10... I'll update the Linux version in next weeks just after the Windows version

**Comment by jiminorris** [comment]
If I execute ./install directly I get this:

`Updating build configuration files for Ultrastar Deluxe WorldParty, please wait...
./autogen.sh: 10: ./autogen.sh: autoreconf: not found
./install: line 3: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for 'install'.
cp: cannot create regular file '/usr/share/applications/WorldParty.desktop': Permission denied
`

Only that last line is any different

**Comment by TeLiXj** [comment]
Can you try the last alfa version??? I'm sure that your problem was that didn't have autoconf package installed.
And try to execute install as sudo to get necessary permissions

**Comment by jiminorris** [comment]
Yes, sorry, autoconf is the problem. Thanks.
