### ISSUE TITLE
Leaderboard servers

### ISSUE THREAD

**Issue by MairusuPawa** [ultrastares/usdxworldparty#3]
Hello!

USDX World Party comes with online leaderboards support. It seems that the end-user can select a server to connect to, the default one being Ultrastar-ES. However, I did not find any documentation on how to add you own server - or on own to run one yourself. Do you have more information regarding this?

**Comment by ariscop** [comment]
Been working on this on such a dll, https://github.com/ariscop/mlkhs
We haven't built a server yet, but the dll 'works' in that it should be capable of talking to a server if you create one.
I'm in favor of replacing the current api (nowhere to store state, 'EncryptPassword', 'EncryptScore'), but this should work as a holdover until the new code is up to speed.

Haven't had a chance to test multiple dlls, the code for it looks a little shaky (it's fond of globals), and probably hasn't seen any use.
