### ISSUE TITLE
EAccessViolation when starting

### ISSUE THREAD

**Issue by deuteragenie** [ultrastares/usdxworldparty#58]
Snap 21.04, rev 60, on Ubuntu 21.04 freshly installed.

I get Unhandled Excpetions / EAccessViolations upon start (at $041FFD7).

**Comment by TeLiXj** [comment]
It's sad but works as expected: it fails on first start and on second must work although they appear similar errors

**Comment by VDK-BRB** [comment]
Why this issue was closed? Is there any solution?

I have the same problem with Windows 10 and after adding some 2900 songs:


_

> An unhandled exception occured at $00410012:
> EAccessViolation: Acces violation
> $00410012
> $0040AA2C
> $00408F8C
> $00412308
> $00444854 _CONSOLEWRITTELN, line 414 of base/UCommon.pas
> $00444917 CONSOLEHANDLERFUNC, line 440 of base/UCommon.pas
> $00403DCF
> $76D0FA29
> $77907A7E
> $77907A4E

_

thx in advance

**Comment by TeLiXj** [comment]
It's closed because I can't (don't know) fix it and doesn't affect to play the game.
