### ISSUE TITLE
new key shortcut for medley interference

### ISSUE THREAD

**Issue by grgohr** [ultrastares/usdxworldparty#60]
Hello, on Windows 10 (UltraStar.WorldParty.21.02), the new key shortcut for Medley (previously D) does not work as it switches between fullscreen and window mode (Windows takes the lead on that).
probably a better idea to stick to function keys (F8 and F9 still seem available)

[Alt + Enter] Cantar 5 versiones cortas de forma aleatoria.
https://ultrastar-es.org/es/ayuda/10/tutorial/9391

thanks

PS: I figured out that SHIFT+ALT+ENTER works as a workaround

**Comment by Daniel20Ultrastar-es** [comment]
In a future it's going to be impossible to have all options in function keys, but in song menu (F10 or right button mouse) you have the medley feature.

**Comment by TeLiXj** [comment]
The shortcut is `Shift+Enter` in the help page and in the code. `Alt` only is used to show order window with `F10` or to jump to artists letter.
