### ISSUE TITLE
config.ini file and .ultrastar-worldparty directory missing

### ISSUE THREAD

**Issue by wilson102** [ultrastares/usdxworldparty#61]
Hi, I've installed Ultrastar-WorldParty using snap on my Raspberry Pi 4, running Ubuntu 21.1. Whilst trying to add songs to the game I can't find either the .ultrastar-worldparty directory or the config.ini file. I've shared a screenshot showing the location where the folder should be but it is not there. 

Looking for the config.ini file in /snap/ultrastar-worldparty/current/.ultrastar-worldparty as stated on the snap website. 

![Screenshot 2021-09-09 at 15 29 18](https://user-images.githubusercontent.com/63445054/132706251-4aa6f170-d071-41a3-9f03-8a015b8e5dcf.png)

**Comment by TeLiXj** [comment]
Note that the folder is 
`~/snap/ultrastar-worldparty/current/.ultrastar-worldparty`
not
`/snap/ultrastar-worldparty/current/.ultrastar-worldparty `

**Comment by Tarantinio** [comment]
I have the same Problem. I cant find the Path or the file
