### ISSUE TITLE
Showing "notes" even though micro is turned off/ not singing

### ISSUE THREAD

**Issue by LiFaytheGoblin** [ultrastares/usdxworldparty#63]
Hi all!

Today I decided to play around with UltraStar. So I connected my headset. The song started and it showed "notes" even though I was not singing. I thought it might be background noise so I pressed the sound off button on my headset. Still showing notes. How is this possible? There is no other mic connected to my desktop computer, I made sure of that.

- Ubuntu
- I restarted ALSA

Thanks!

**Comment by TeLiXj** [comment]
Every system have an internal line! 
Please, ask your support questions to the forum https://ultrastar-es.org/foro
