### ISSUE TITLE
Can't install snap package on RaspberryPi OS (armhf architecture)

### ISSUE THREAD

**Issue by Kapcash** [ultrastares/usdxworldparty#67]
Hello there!

I'm trying to install the latest Ultrastar WorldParty on a RaspberryPi OS (following these [instructions](https://snapcraft.io/install/usdxworldparty/raspbian)) but I get an error saying there is no package available for this archicteture (armhf)

> ```bash
> $ sudo snap install usdxworldparty
> error: snap "usdxworldparty" is not available on this architecture (armhf) but exists in other architectures (amd64, arm64, i386)
> ```

Setup:
* Hardware: RaspberryPi 2 _(Will upgrade to RaspberryPi 4 soon though)_
* OS: **RaspberryPi OS 11** (bullseye)

I saw that it should exist and be installable without problem...
Is this normal? Should I compile it myself from the sources? (This method worked well with the old UltrastarDeluxe but it's laggy as hell haha)

**Comment by TeLiXj** [comment]
That snap isn't the official, is an old build made by one of our collaborators.
You must try https://snapcraft.io/ultrastar-worldparty
