### ISSUE TITLE
Avatar no png transparency

### ISSUE THREAD

**Issue by Thaddell** [ultrastares/usdxworldparty#68]
Don't really know if it's an issue or not, but for the png avatar pictures it's not possible to make them half transparrent. Tried for a long time, but can't seem to find a way in the themes.ini or other editable files. Now I have circle croped avatar pictures which show black borders ingame...

**Comment by TeLiXj** [comment]
The game supports PNG transparency but I suspects that just in avatars is disabled on purpose. I'll return to give you an answer before release the new version.

**Comment by Thaddell** [comment]
I think I found the issue by myself. In the uAvatar is a line where I just changed the PLAIN to TRANSPARENT and now it is working fine

**Comment by TeLiXj** [comment]
as I said... xD
I'll change it in the new version
