### ISSUE TITLE
USWP not running after update

### ISSUE THREAD

**Issue by frogro** [ultrastares/usdxworldparty#69]
Hi, USWP was running for a few months great on my Raspi 4. The Pi has not been connected to the internet during this time. After having conntected the Pi to the internet again, uswp was removed into another folder. In consequence uswp could not been started anymore. There must have been some kind of update, maybe on snap, i do not know... i tried to remove uswp via the snap store, but removing was not successful. I got a message that there is an auto-update process  running on uswp... any idea how i can remove snap and uswp completly to reinstall?

**Comment by TeLiXj** [comment]
It's very strange because the update is only for minor fixes of packages used by the game. You can try use `snap remove --purge ultrastar-worldparty` to remove completely all files.

**Comment by frogro** [comment]
It was possibke ro completly remove Uswp with abive mentioned command and to reinstall from snap store. Thx
