### ISSUE TITLE
Pi Camera nit detected as device cam

### ISSUE THREAD

**Issue by frogro** [ultrastares/usdxworldparty#70]
Hi, I use a Pi Cam v2.1 in my setup, but the cam is not detected as device cam. So preview is not possible. In chromium-browser e.g. the cam works fine. Any idea?

**Comment by TeLiXj** [comment]
the webcam support is very rudimentary and never was developed using a raspberry pi, so it's normal that it doesn't work... and will never work

**Comment by TeLiXj** [comment]
I close this issue, maybe a future upgrade of webcam support fix your Pi Cam.
