### ISSUE TITLE
Use rotary encode to navigate through the gui

### ISSUE THREAD

**Issue by frogro** [ultrastares/usdxworldparty#71]
This would be a further improvement: it would be nice to navigate through the menu with a rotary encoder connected to the gpios of the Pi.

**Comment by TeLiXj** [comment]
I can't see the improvement because you need something else to use other game sections

**Comment by frogro** [comment]
Ok. It would be an improvement for me ... :-) I use uswp in a photobooth as a second application. The photobooth can be controlled with the rotary encoder. So it would be nice to have this feature

**Comment by TeLiXj** [comment]
I know, but you have to understand that in this game the development has a million things to do first for the vast majority of the people ;)
