### ISSUE TITLE
Clarification re: license

### ISSUE THREAD

**Issue by YoshiRulz** [ultrastares/usdxworldparty#73]
In https://github.com/ultrastares/ultrastar-worldparty/commit/5c4c081c9199707a531bb6c60244fc832cb326b9, the "or later" wording which indicated GPLv3+ was removed, leaving it as GPLv3 only. But Snapcraft still reads GPLv3+. Which is it?

**Comment by TeLiXj** [comment]
in what file? I only can remember GPLv3 in all cases
Snapcraft uses the information stored here https://github.com/ultrastares/ultrastar-worldparty/blob/master/snap/snapcraft.yaml
and as you can see appear `license: GPL-3.0`, I don't know why the info in the website add the `+` or `later`. But doesn't care, this program always be GPL 3, 4, 5 or whatever
