### ISSUE TITLE
Feature request: More compact song selection screen (Text list)

### ISSUE THREAD

**Issue by Edi316** [ultrastares/usdxworldparty#74]
Is it possible to add a song selection screen option, that is more compact then the current list view? (something like a text list view)

This would make navigating a large song collection with only a game controller much easier and faster.

To demonstrate, what I mean, here is a screenshot from Vocaluxe, which has this kind of option:
![Voca](https://user-images.githubusercontent.com/61267443/205759011-7bf5cd1f-a87e-45da-baa4-b9a5fd6bd09f.jpg)

**Comment by TeLiXj** [comment]
Added in f7dd8806112dbc1510a2f2c01bfa7a540dd0923e
