### ISSUE TITLE
Typo: Game settings

### ISSUE THREAD

**Issue by zofoklecja** [ultrastares/usdxworldparty#82]
I found typo in Game settings
![image](https://github.com/ultrastares/ultrastar-worldparty/assets/8929565/6ee1f5d1-ae6a-432d-8aca-91c288fc335f)
One of the options says "Medyley calcultated" instead of "Medley calculated"

I'd be happy to fix this myself if allowed. Seems like a good beginner issue

**Comment by Daniel20Ultrastar-es** [comment]
this is already fixed in the very next version of the game
