### ISSUE TITLE
Make keyboard shortcuts info available in program

### ISSUE THREAD

**Issue by zofoklecja** [ultrastares/usdxworldparty#83]
Currently the list of shortcuts is available only on UltraStar Espana website (https://ultrastar-es.org/en/ayuda/10/tutorial/9391) in Spanish.

I think it would be nice to have it also available in program (maybe in sub-screen of About). We usually play with TV plugged in and keyboard as a main controller. As a lazy power user I'd love to be able to check things when I need them, without reaching for my phone and googling 😇 

Thank you!

**Comment by Daniel20Ultrastar-es** [comment]
All parts of the game will be accesible using the mouse or the keyboard, for those shorcuts which are "hide" will be shown and editable from a new section "shortcuts" that will be implemented in the next of the next version
