### ISSUE TITLE
New Avatar Add-On for Ultrastar

### ISSUE THREAD

**Issue by marwin89** [ultrastares/usdxworldparty#85]
Dear Worldparty maintainers,

I've updated my free avatar collection for vocaluxe and ultrastar  - with 100 new pics.  You can use it for ultrastar worldparty community as well. Please just spread the word.

**Comment by Daniel20Ultrastar-es** [comment]
thanks @marwin89 for your initiative. We already changed all avatars for the next version. It would be great if you could share the avatars in our site in add-on section: https://ultrastar-es.org/foro/viewforum.php?f=5 many people will love this.

Regards

**Comment by marwin89** [comment]
Hi @Daniel20Ultrastar-es , thanks for the fast reply. 
I've created a post: https://ultrastar-es.org/foro/viewtopic.php?t=13924
It would be nice if the thread is pinned.

**Comment by TeLiXj** [comment]
Pinned!
