### ISSUE TITLE
Meta-Project: Future of UltraStar TXT-Format

### ISSUE THREAD

**Issue by marwin89** [ultrastares/usdxworldparty#88]
Dear World-Party Team,
 
in case you didn't heard of it - there is a **new meta-project** for all karaoke games just called **"format"**. 
Big Goal is to **standardize and versionize the ultrastar txt-format** (for every game, editor, tool, txt-file-hosting, usdbsyncer etc.). 

Every developer of games, editors etc. can bring themselves in and **shape the future of the format**

maybe you wanna watch the project or contribute sometimes. Everyone would be happy to have you on board as well.

Its promising, it started in september and there are already important devs from different communites and software: 
**performous, melody mania, ultrastar deluxe, usdb-syncer, us manager, ultrasinger etc**

There's is much consens and connection. Let's join forces and improve the format we all love together.

**Comment by TeLiXj** [comment]
We don't collaborate with any project from that team. We will continue using the format as we want.
