### ISSUE TITLE
Song with just a special character as title crashes ultrastar worldparty

### ISSUE THREAD

**Issue by IchbinkeinReh** [ultrastares/usdxworldparty#95]
Steps to reproduce:
1. Unzip [CrashSong.zip](https://github.com/ultrastares/ultrastar-worldparty/files/14844844/CrashSong.zip) and put it into your song folder
2. Configure folder mode to be enabled
3. Start ultrastar worldparty and go to song list
4. Crash happens

Alternatively to step 1, just open any song and replace the TITLE with just a questionmark (eg #TITLE:? )

![Screenshot 2024-04-03 205902](https://github.com/ultrastares/ultrastar-worldparty/assets/12527468/532a8488-e417-4ae7-8435-a545a94a7b91)

**Comment by Daniel20Ultrastar-es** [comment]
It works perfectly in stable and development version, Have you tried in other computer?

**Comment by IchbinkeinReh** [comment]
Thank you very much for the quick reply. I could not reproduce it anymore. I could swear i tested i a few times before i opened the issue. However i 

@Daniel20Ultrastar-es may i ask you about another issue i have? I have a pretty big collection of songs (~24000) when i try to load them with UltraStar Deluxe i have no problems bit it takes ~10 minutes till it starts, with UltraStar WorldParty it starts withing 30 seconds which is impressive. Songs load fine in main menu, but as soon as i want to go to the song list this crash happens
![Screenshot 2024-04-03 194210](https://github.com/ultrastares/ultrastar-worldparty/assets/12527468/3367662b-e564-441c-b979-8f65f11756ac)
Any idea what i can do?

I already experimented a bit and it seems to be no specific song but just the total amount of songs. if i split the songs into different folders and only load ~21000 then i can access the song list.

**Comment by IchbinkeinReh** [comment]
@Daniel20Ultrastar-es i was able to reproduce the issue again. It only happens if folder mode is enabled!

**Comment by Daniel20Ultrastar-es** [comment]
I don't have such a large number of songs, but surely the problem comes from a defective song. Folder mode should works fine.

we only support songs from our website. Many of the songs coming from other websites, such as USDB, contain **MANY** bugs.

Edit: this bug is already fixed in the development version

**Comment by IchbinkeinReh** [comment]
ok thank you. then i will close this issue. is there any place i can download development builds or do i need to compile myself?

**Comment by Daniel20Ultrastar-es** [comment]
we'll release a new version in the coming months (surely for summer), until then, you can compile yourself the development builds.
